site_name: Matrix CLI — MatrixHub
site_description: "MatrixHub CLI: search, install, run, and manage agents & MCP servers"
site_url: https://matrixhub.io
copyright: "© 2025 MatrixHub"

# Polished, accessible theme with great navigation & search
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: cyan

nav:
  - Home: index.md
  - Install: install.md
  - Quickstart: quickstart.md
  - MCP (Probe & Call): mcp.md
  - Runtime (run/ps/logs): runtime.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
