# mkdocs.yml
site_name: Matrix CLI
site_description: Official command-line interface for Matrix Hub
site_url: https://agent-matrix.github.io/matrix-cli/
repo_name: agent-matrix/matrix-cli
repo_url: https://github.com/agent-matrix/matrix-cli
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - toc.follow
  language: en

nav:
  - Home: index.md
  - Getting Started:
      - Configuration: configuration.md
      - Commands: commands.md
  - Reference: reference.md
  - Examples: examples.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/agent-matrix
