# .github/workflows/release.yml
# Build distributions on GitHub Release and publish to PyPI via OIDC (Trusted Publishing)

name: Build & Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: write   # upload assets to the GitHub release
  id-token: write   # required for OIDC / trusted publishing

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip build

      - name: Build wheel and sdist
        run: python -m build

      - name: Upload artifacts to the GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz

      - name: Persist artifacts for publish job
        uses: actions/upload-artifact@v4
        with:
          name: python-dists
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/project/matrix-cli/
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-dists
          path: dist/

      - name: Publish via Trusted Publishing
        uses: pypa/gh-action-pypi-publish@release/v1
